### ISSUE TITLE
error on generating 

### ISSUE THREAD

**Issue by AjeethT** [IBM/raft-fabric-sample#17]
##########################################################
##########################################################
+ cryptogen generate --config=./crypto-config.yaml
./byfn.sh: line 362: /home/hyperledger/Downloads/raft-fabric-sample-master/first-network/../bin/cryptogen: cannot execute binary file: Exec format error
+ res=126
+ set +x
Failed to generate certificates...

**Comment by horeaporutiu** [comment]
@AjeethT Are you using a Linux based system? please check these instructions - https://github.com/IBM/raft-fabric-sample#for-linux-users

**Comment by horeaporutiu** [comment]
@AjeethT Let me know if that solved it.

**Comment by AjeethT** [comment]
not yet solved

**Comment by AjeethT** [comment]
> @AjeethT Are you using a Linux based system? please check these instructions - https://github.com/IBM/raft-fabric-sample#for-linux-users

yes im using linux system

**Comment by horeaporutiu** [comment]
are you using ubuntu? What is your version number? 

@AjeethT

**Comment by AjeethT** [comment]
18

**Comment by guilhermelionzo** [comment]
@AjeethT, probably this issue occurred due to the old version of binaries files (**bin folder**). Try to download this version here:
`curl -L --retry 5 --retry-delay 3 https://github.com/hyperledger/fabric/releases/download/v2.0.0/hyperledger-fabric-linux-amd64-2.0.0.tar.gz | tar xz || rc= 0`

After download, replace the project **bin folder** to the new one, that was downloaded. This should solve the problem.

**Comment by horeaporutiu** [comment]
were you able to solve this @AjeethT ?
